export type AllianceCamp = "us_nato" | "china_russia" | "neutral";
export type Stability = "Stable" | "Shifting" | "Volatile";
export type Trend = "Moving toward US bloc" | "Moving toward China bloc" | "Becoming more neutral" | "Stable";
export type InvestmentSignal = "Opportunity" | "Watch" | "Avoid";
export type ScoreTrend = "up" | "stable" | "down";

export const DETERMINANT_LABELS: Record<string, string> = {
  education: "Education",
  competitiveness: "Competitiveness",
  economicOutput: "GDP Output",
  military: "Military",
  tradeShare: "Trade Share",
  financialCenter: "Financial Center",
  reserveCurrency: "Reserve Currency",
  debtLevels: "Debt Health",
  wealthGaps: "Equality",
  politicalCohesion: "Cohesion",
  ruleOfLaw: "Rule of Law",
  infrastructure: "Infrastructure",
  characterValues: "Values",
  naturalResources: "Resources",
  alliances: "Alliances",
  technology: "Technology",
  costCompetitiveness: "Cost Edge",
  leadershipQuality: "Leadership",
};

export const DETERMINANT_KEYS = Object.keys(DETERMINANT_LABELS);

export const CAMP_COLORS: Record<AllianceCamp, string> = {
  us_nato: "#3b82f6",
  china_russia: "#ef4444",
  neutral: "#eab308",
};

export const CAMP_LABELS: Record<AllianceCamp, string> = {
  us_nato: "US/NATO",
  china_russia: "China/Russia",
  neutral: "Neutral",
};

export const SIGNAL_COLORS: Record<InvestmentSignal, string> = {
  Opportunity: "#22c55e",
  Watch: "#eab308",
  Avoid: "#ef4444",
};

export type CountryData = {
  name: string;
  code: string;
  allianceCamp: AllianceCamp;
  unAlignmentUS: number;
  unAlignmentChina: number;
  primaryTradePartner: string;
  keyTreaties: string;
  stability: Stability;
  trend: Trend;
  scores: Record<string, number>;
  scoreTrends: Record<string, ScoreTrend>;
  scoreEvidence: Record<string, string>;
  investment: {
    signal: InvestmentSignal;
    reasoning: string;
    relatedAssets: string[];
  };
};

export const countries: CountryData[] = [
  {
    name: "United States",
    code: "US",
    allianceCamp: "us_nato",
    unAlignmentUS: 100,
    unAlignmentChina: 12,
    primaryTradePartner: "Canada/Mexico",
    keyTreaties: "NATO, AUKUS, USMCA, Quad",
    stability: "Stable",
    trend: "Stable",
    scores: {
      education: 8, competitiveness: 9, economicOutput: 10, military: 10,
      tradeShare: 8, financialCenter: 10, reserveCurrency: 10, debtLevels: 3,
      wealthGaps: 4, politicalCohesion: 4, ruleOfLaw: 8, infrastructure: 7,
      characterValues: 7, naturalResources: 8, alliances: 10, technology: 10,
      costCompetitiveness: 5, leadershipQuality: 5,
    },
    scoreTrends: {
      education: "stable", competitiveness: "stable", economicOutput: "stable", military: "up",
      tradeShare: "down", financialCenter: "stable", reserveCurrency: "down", debtLevels: "down",
      wealthGaps: "down", politicalCohesion: "down", ruleOfLaw: "stable", infrastructure: "stable",
      characterValues: "down", naturalResources: "up", alliances: "stable", technology: "up",
      costCompetitiveness: "down", leadershipQuality: "down",
    },
    scoreEvidence: {
      education: "Top universities globally but K-12 declining in OECD rankings",
      competitiveness: "World's largest venture capital ecosystem, Silicon Valley dominance",
      economicOutput: "$28T GDP, 25% of world output",
      military: "$900B+ defence budget, global force projection, Iran war ongoing",
      tradeShare: "Largest importer, reshoring reducing trade openness",
      financialCenter: "NYSE + NASDAQ = 60% of global equity market cap",
      reserveCurrency: "USD 58% of global reserves but declining from 72% in 2000",
      debtLevels: "$36T national debt, 125% debt-to-GDP, unsustainable trajectory",
      wealthGaps: "Top 1% own 32% of wealth, worst among developed nations",
      politicalCohesion: "Deep partisan divide, contested elections, institutional erosion",
      ruleOfLaw: "Independent judiciary but politicisation concerns growing",
      infrastructure: "ASCE grades US infrastructure C-, massive backlog",
      characterValues: "Innovation culture strong but social cohesion declining",
      naturalResources: "Net energy exporter since 2019, abundant shale reserves",
      alliances: "50+ treaty allies, NATO anchor, Quad, AUKUS",
      technology: "AI leadership (OpenAI, Google, Anthropic), semiconductor design dominance",
      costCompetitiveness: "High labour costs offset by productivity and automation",
      leadershipQuality: "Polarised leadership, short-term policy focus",
    },
    investment: {
      signal: "Opportunity",
      reasoning: "Despite fiscal challenges, US tech and energy dominance drives returns. Defence spending surge from Iran war benefits industrial base.",
      relatedAssets: ["SPY", "XLE", "QQQ"],
    },
  },
  {
    name: "China",
    code: "CN",
    allianceCamp: "china_russia",
    unAlignmentUS: 15,
    unAlignmentChina: 92,
    primaryTradePartner: "ASEAN/EU",
    keyTreaties: "SCO, RCEP, BRI, BRICS+",
    stability: "Stable",
    trend: "Stable",
    scores: {
      education: 7, competitiveness: 8, economicOutput: 9, military: 8,
      tradeShare: 10, financialCenter: 5, reserveCurrency: 3, debtLevels: 4,
      wealthGaps: 4, politicalCohesion: 6, ruleOfLaw: 3, infrastructure: 8,
      characterValues: 6, naturalResources: 5, alliances: 6, technology: 8,
      costCompetitiveness: 8, leadershipQuality: 6,
    },
    scoreTrends: {
      education: "up", competitiveness: "up", economicOutput: "stable", military: "up",
      tradeShare: "up", financialCenter: "up", reserveCurrency: "up", debtLevels: "down",
      wealthGaps: "stable", politicalCohesion: "down", ruleOfLaw: "stable", infrastructure: "up",
      characterValues: "stable", naturalResources: "stable", alliances: "up", technology: "up",
      costCompetitiveness: "down", leadershipQuality: "stable",
    },
    scoreEvidence: {
      education: "Most STEM graduates globally, rising university rankings",
      competitiveness: "World's manufacturing hub, EV and solar dominance",
      economicOutput: "$18T GDP, second largest economy, slowing growth 4-5%",
      military: "$280B+ defence budget, 7% annual increase, Taiwan threat posture",
      tradeShare: "Largest trading nation, 15% of global exports",
      financialCenter: "Shanghai growing but capital controls limit openness",
      reserveCurrency: "RMB 2.5% of reserves, BRICS push for alternatives",
      debtLevels: "330% total debt-to-GDP including local government, property crisis",
      wealthGaps: "Gini coefficient 0.47, urban-rural divide significant",
      politicalCohesion: "Centralised control but youth unemployment 15%+, property wealth destroyed",
      ruleOfLaw: "Party above law, unpredictable regulatory crackdowns",
      infrastructure: "World-class HSR and 5G, but overbuilt in many regions",
      characterValues: "Strong work ethic, long-term planning culture",
      naturalResources: "Rare earth dominance (60% global supply) but energy importer",
      alliances: "SCO, BRICS+, BRI — growing non-Western coalition",
      technology: "AI close second to US, Huawei 5G, but semiconductor bottleneck",
      costCompetitiveness: "Rising wages reducing edge, moving up value chain",
      leadershipQuality: "Xi centralised power — efficient but brittle, no succession plan",
    },
    investment: {
      signal: "Watch",
      reasoning: "Manufacturing and tech capabilities are world-class but property crisis, demographic decline, and Taiwan risk create uncertainty. Uninvestable for many Western funds.",
      relatedAssets: ["FXI", "KWEB", "MCHI"],
    },
  },
  {
    name: "Russia",
    code: "RU",
    allianceCamp: "china_russia",
    unAlignmentUS: 8,
    unAlignmentChina: 88,
    primaryTradePartner: "China/India",
    keyTreaties: "SCO, CSTO, BRICS+",
    stability: "Volatile",
    trend: "Moving toward China bloc",
    scores: {
      education: 6, competitiveness: 3, economicOutput: 3, military: 8,
      tradeShare: 3, financialCenter: 2, reserveCurrency: 1, debtLevels: 7,
      wealthGaps: 3, politicalCohesion: 5, ruleOfLaw: 2, infrastructure: 4,
      characterValues: 5, naturalResources: 9, alliances: 4, technology: 4,
      costCompetitiveness: 6, leadershipQuality: 3,
    },
    scoreTrends: {
      education: "down", competitiveness: "down", economicOutput: "down", military: "down",
      tradeShare: "down", financialCenter: "down", reserveCurrency: "down", debtLevels: "stable",
      wealthGaps: "down", politicalCohesion: "down", ruleOfLaw: "down", infrastructure: "down",
      characterValues: "down", naturalResources: "stable", alliances: "down", technology: "down",
      costCompetitiveness: "stable", leadershipQuality: "down",
    },
    scoreEvidence: {
      education: "Brain drain accelerating — 500k+ educated Russians emigrated since 2022",
      competitiveness: "Sanctions destroyed integration with global economy",
      economicOutput: "$1.9T GDP, now smaller than Italy, war economy distortion",
      military: "Large nuclear arsenal and experienced army but Ukraine exposed equipment losses",
      tradeShare: "Sanctioned from Western trade, dependent on China/India for oil sales",
      financialCenter: "Cut off from SWIFT, Moscow exchange isolated",
      reserveCurrency: "Ruble not a reserve currency, $300B reserves frozen",
      debtLevels: "Low government debt (20% GDP) but hidden war spending costs",
      wealthGaps: "Oligarch wealth extreme, 35% of wealth held by 500 individuals",
      politicalCohesion: "Authoritarian control holds but war fatigue growing",
      ruleOfLaw: "Arbitrary property seizures, no independent judiciary",
      infrastructure: "Soviet-era infrastructure crumbling outside Moscow/St Petersburg",
      characterValues: "Resilience culture but innovation suppressed by state control",
      naturalResources: "World's largest country — oil, gas, minerals, timber, arable land",
      alliances: "Junior partner to China, losing influence in Central Asia",
      technology: "Falling behind, semiconductor sanctions bite, Yandex brain drain",
      costCompetitiveness: "Low wages but poor productivity and isolated supply chains",
      leadershipQuality: "Putin centralised power, succession crisis risk",
    },
    investment: {
      signal: "Avoid",
      reasoning: "Sanctioned, inaccessible to Western investors, structural decline accelerating. Resource wealth trapped behind political risk.",
      relatedAssets: [],
    },
  },
  {
    name: "Germany",
    code: "DE",
    allianceCamp: "us_nato",
    unAlignmentUS: 82,
    unAlignmentChina: 18,
    primaryTradePartner: "EU/China",
    keyTreaties: "NATO, EU, Franco-German Treaty",
    stability: "Shifting",
    trend: "Moving toward US bloc",
    scores: {
      education: 8, competitiveness: 8, economicOutput: 7, military: 5,
      tradeShare: 8, financialCenter: 6, reserveCurrency: 7, debtLevels: 7,
      wealthGaps: 6, politicalCohesion: 5, ruleOfLaw: 9, infrastructure: 7,
      characterValues: 8, naturalResources: 3, alliances: 8, technology: 7,
      costCompetitiveness: 5, leadershipQuality: 6,
    },
    scoreTrends: {
      education: "stable", competitiveness: "down", economicOutput: "down", military: "up",
      tradeShare: "stable", financialCenter: "stable", reserveCurrency: "stable", debtLevels: "down",
      wealthGaps: "stable", politicalCohesion: "down", ruleOfLaw: "stable", infrastructure: "down",
      characterValues: "stable", naturalResources: "stable", alliances: "up", technology: "stable",
      costCompetitiveness: "down", leadershipQuality: "up",
    },
    scoreEvidence: {
      education: "Strong vocational system, top engineering universities",
      competitiveness: "Automotive crisis (EV transition), energy cost disadvantage",
      economicOutput: "$4.5T GDP but in mild recession, industrial model under pressure",
      military: "€100B+ special fund, defence spending doubling to 3.5% GDP by 2028",
      tradeShare: "Export powerhouse but China dependency creates vulnerability",
      financialCenter: "Frankfurt ECB hub but limited compared to London/NY",
      reserveCurrency: "Euro is second global reserve currency at 20%",
      debtLevels: "60% debt-to-GDP, fiscal discipline but Schuldenbremse suspended for defence",
      wealthGaps: "Low income inequality but high wealth concentration",
      politicalCohesion: "Coalition instability, AfD rising, east-west divide persists",
      ruleOfLaw: "Strong independent judiciary, constitutional court respected",
      infrastructure: "Deutsche Bahn declining, digital infrastructure lagging",
      characterValues: "Engineering excellence culture, strong institutional trust",
      naturalResources: "Minimal — energy import dependent, coal phaseout",
      alliances: "NATO core member, EU anchor, strengthening Transatlantic ties post-Ukraine",
      technology: "Strong industrial tech (SAP, Siemens) but lagging in AI/cloud",
      costCompetitiveness: "High energy and labour costs eroding manufacturing edge",
      leadershipQuality: "New government more decisive on defence and energy independence",
    },
    investment: {
      signal: "Watch",
      reasoning: "Rapidly rearming and building energy independence. Defence sector booming but high China trade exposure creates transition vulnerability. Industrial model in flux.",
      relatedAssets: ["EWG", "RHM.DE", "EUAD.L"],
    },
  },
  {
    name: "India",
    code: "IN",
    allianceCamp: "neutral",
    unAlignmentUS: 42,
    unAlignmentChina: 48,
    primaryTradePartner: "US/UAE/China",
    keyTreaties: "Quad, BRICS+, SCO (observer)",
    stability: "Stable",
    trend: "Moving toward US bloc",
    scores: {
      education: 5, competitiveness: 6, economicOutput: 7, military: 7,
      tradeShare: 5, financialCenter: 4, reserveCurrency: 1, debtLevels: 6,
      wealthGaps: 3, politicalCohesion: 5, ruleOfLaw: 5, infrastructure: 4,
      characterValues: 6, naturalResources: 5, alliances: 7, technology: 7,
      costCompetitiveness: 9, leadershipQuality: 7,
    },
    scoreTrends: {
      education: "up", competitiveness: "up", economicOutput: "up", military: "up",
      tradeShare: "up", financialCenter: "up", reserveCurrency: "stable", debtLevels: "stable",
      wealthGaps: "stable", politicalCohesion: "stable", ruleOfLaw: "stable", infrastructure: "up",
      characterValues: "stable", naturalResources: "stable", alliances: "up", technology: "up",
      costCompetitiveness: "stable", leadershipQuality: "stable",
    },
    scoreEvidence: {
      education: "IITs world-class but mass education quality poor, improving fast",
      competitiveness: "Fastest growing major economy at 6-7%, manufacturing push (Make in India)",
      economicOutput: "$3.9T GDP, fifth largest, will overtake Germany by 2028",
      military: "$75B defence budget, third largest, nuclear power, Quad member",
      tradeShare: "Growing but still only 2.5% of global exports",
      financialCenter: "Mumbai growing, GIFT City new financial hub, but capital controls",
      reserveCurrency: "Rupee not a reserve currency, but bilateral trade settlement growing",
      debtLevels: "83% government debt-to-GDP, manageable given growth rate",
      wealthGaps: "Extreme inequality — richest 1% own 40% of wealth",
      politicalCohesion: "Modi's BJP dominance provides stability but religious tensions",
      ruleOfLaw: "Independent but slow judiciary, improving regulatory framework",
      infrastructure: "Massive investment in highways, airports, metro — still behind",
      characterValues: "Young, entrepreneurial population, strong diaspora network",
      naturalResources: "Limited oil/gas, good solar potential, rare earth deposits",
      alliances: "Strategic neutrality — buys Russian oil AND joins US Quad. Maximum optionality.",
      technology: "IT services global leader, UPI payments revolutionary, AI growing",
      costCompetitiveness: "Largest competitive advantage — young, cheap, English-speaking workforce",
      leadershipQuality: "Modi provides continuity and reform momentum through 2029",
    },
    investment: {
      signal: "Opportunity",
      reasoning: "Neutral alliance capturing trade from US-China decoupling while domestic growth accelerates. Fastest growing large economy with young demographics.",
      relatedAssets: ["INDA", "INDY", "SMIN"],
    },
  },
  {
    name: "Norway",
    code: "NO",
    allianceCamp: "us_nato",
    unAlignmentUS: 90,
    unAlignmentChina: 10,
    primaryTradePartner: "EU/UK",
    keyTreaties: "NATO, EEA, Nordic Defence Cooperation",
    stability: "Stable",
    trend: "Stable",
    scores: {
      education: 8, competitiveness: 7, economicOutput: 3, military: 4,
      tradeShare: 2, financialCenter: 3, reserveCurrency: 1, debtLevels: 10,
      wealthGaps: 9, politicalCohesion: 9, ruleOfLaw: 10, infrastructure: 8,
      characterValues: 9, naturalResources: 9, alliances: 8, technology: 6,
      costCompetitiveness: 3, leadershipQuality: 8,
    },
    scoreTrends: {
      education: "stable", competitiveness: "stable", economicOutput: "up", military: "up",
      tradeShare: "up", financialCenter: "stable", reserveCurrency: "stable", debtLevels: "stable",
      wealthGaps: "stable", politicalCohesion: "stable", ruleOfLaw: "stable", infrastructure: "stable",
      characterValues: "stable", naturalResources: "up", alliances: "stable", technology: "stable",
      costCompetitiveness: "stable", leadershipQuality: "stable",
    },
    scoreEvidence: {
      education: "Top PISA scores, free university education, high literacy",
      competitiveness: "Small economy but efficient, strong sovereign wealth fund",
      economicOutput: "$580B GDP, small but per-capita among world's highest",
      military: "Small forces but NATO border with Russia, increasing to 2.5% GDP",
      tradeShare: "Tiny share of global trade, primarily energy exports",
      financialCenter: "Oslo Børs small, NBIM ($1.7T) is influence mechanism",
      reserveCurrency: "NOK not a reserve currency",
      debtLevels: "Near zero net debt — $1.7T sovereign wealth fund vs $200B debt",
      wealthGaps: "Among world's most equal income distribution",
      politicalCohesion: "High trust society, consensus-based politics",
      ruleOfLaw: "Consistently top 3 globally in rule of law indices",
      infrastructure: "Excellent for population size, massive tunnel/bridge investment",
      characterValues: "Trust-based society, strong work-life balance culture",
      naturalResources: "Major oil/gas exporter, hydropower, fish, minerals — Hormuz crisis windfall",
      alliances: "NATO founding member, strong US/UK ties, Nordic cooperation",
      technology: "Strong in maritime tech, energy tech, but small scale",
      costCompetitiveness: "Highest labour costs in Europe",
      leadershipQuality: "Stable democratic governance, long-term oriented via NBIM",
    },
    investment: {
      signal: "Opportunity",
      reasoning: "Energy exporter benefiting directly from Stagflation regime. NATO member with no China exposure. Sovereign wealth fund provides unmatched stability.",
      relatedAssets: ["NORW", "EQNR", "NHY.OL"],
    },
  },
  {
    name: "Saudi Arabia",
    code: "SA",
    allianceCamp: "neutral",
    unAlignmentUS: 38,
    unAlignmentChina: 52,
    primaryTradePartner: "China/India",
    keyTreaties: "GCC, OPEC+, Abraham Accords (pending)",
    stability: "Shifting",
    trend: "Becoming more neutral",
    scores: {
      education: 4, competitiveness: 5, economicOutput: 4, military: 6,
      tradeShare: 4, financialCenter: 4, reserveCurrency: 1, debtLevels: 8,
      wealthGaps: 3, politicalCohesion: 6, ruleOfLaw: 4, infrastructure: 7,
      characterValues: 4, naturalResources: 10, alliances: 5, technology: 4,
      costCompetitiveness: 7, leadershipQuality: 6,
    },
    scoreTrends: {
      education: "up", competitiveness: "up", economicOutput: "up", military: "up",
      tradeShare: "stable", financialCenter: "up", reserveCurrency: "stable", debtLevels: "stable",
      wealthGaps: "stable", politicalCohesion: "stable", ruleOfLaw: "stable", infrastructure: "up",
      characterValues: "stable", naturalResources: "stable", alliances: "up", technology: "up",
      costCompetitiveness: "stable", leadershipQuality: "stable",
    },
    scoreEvidence: {
      education: "Vision 2030 investing heavily but starting from low base",
      competitiveness: "Diversification push — NEOM, entertainment, tourism",
      economicOutput: "$1.1T GDP, oil wealth concentrated, Vision 2030 diversification",
      military: "$75B defence budget, Yemen experience, but depends on US equipment",
      tradeShare: "Oil exports dominant, trying to diversify",
      financialCenter: "Tadawul growing, Aramco IPO was world's largest",
      reserveCurrency: "SAR pegged to USD, not a reserve currency",
      debtLevels: "Low government debt at 25% GDP, PIF $930B sovereign fund",
      wealthGaps: "Royal family wealth extreme, but social spending increasing",
      politicalCohesion: "MBS centralised power, effective but autocratic",
      ruleOfLaw: "Sharia-based, inconsistent for foreign investors",
      infrastructure: "Massive investment — NEOM, Red Sea Project, Riyadh metro",
      characterValues: "Rapid social modernisation under MBS",
      naturalResources: "World's largest proven oil reserves, solar potential",
      alliances: "Playing US and China against each other — maximum deal optionality",
      technology: "Importing technology rather than building — AI investment fund growing",
      costCompetitiveness: "Low energy costs give industrial advantage",
      leadershipQuality: "MBS effective moderniser but concentration risk",
    },
    investment: {
      signal: "Watch",
      reasoning: "Oil windfall from Hormuz crisis but complex Iran neighbour dynamic. Vision 2030 diversification long-term positive but execution uncertain.",
      relatedAssets: ["KSA", "2222.SR"],
    },
  },
  {
    name: "Brazil",
    code: "BR",
    allianceCamp: "neutral",
    unAlignmentUS: 35,
    unAlignmentChina: 55,
    primaryTradePartner: "China",
    keyTreaties: "BRICS+, Mercosur, US-Brazil Strategic Partnership",
    stability: "Shifting",
    trend: "Becoming more neutral",
    scores: {
      education: 4, competitiveness: 4, economicOutput: 5, military: 4,
      tradeShare: 3, financialCenter: 3, reserveCurrency: 1, debtLevels: 4,
      wealthGaps: 2, politicalCohesion: 3, ruleOfLaw: 4, infrastructure: 3,
      characterValues: 5, naturalResources: 9, alliances: 4, technology: 4,
      costCompetitiveness: 7, leadershipQuality: 4,
    },
    scoreTrends: {
      education: "stable", competitiveness: "stable", economicOutput: "stable", military: "stable",
      tradeShare: "up", financialCenter: "stable", reserveCurrency: "stable", debtLevels: "down",
      wealthGaps: "stable", politicalCohesion: "down", ruleOfLaw: "stable", infrastructure: "stable",
      characterValues: "stable", naturalResources: "stable", alliances: "stable", technology: "stable",
      costCompetitiveness: "stable", leadershipQuality: "down",
    },
    scoreEvidence: {
      education: "Large university system but quality inconsistent, PISA scores below average",
      competitiveness: "Bureaucratic environment, 'custo Brasil' — high costs of doing business",
      economicOutput: "$2.2T GDP, ninth largest, commodity-driven growth",
      military: "Largest in Latin America but underfunded, no power projection",
      tradeShare: "Growing food exports to China, soy/iron ore/oil",
      financialCenter: "B3 exchange growing but BRL volatility deters capital",
      reserveCurrency: "BRL not a reserve currency, but part of BRICS alternative push",
      debtLevels: "78% government debt-to-GDP, high real interest rates",
      wealthGaps: "Among world's most unequal — Gini 0.53",
      politicalCohesion: "Deep Lula vs Bolsonaro divide, institutional stress",
      ruleOfLaw: "Car Wash operation showed judiciary can act, but political interference",
      infrastructure: "Poor logistics, underfunded roads/ports, Amazon preservation tension",
      characterValues: "Creative, entrepreneurial culture, strong social bonds",
      naturalResources: "Amazon, pre-salt oil, arable land, iron ore, rare earths — extraordinary endowment",
      alliances: "BRICS+ active member, hedging between US and China",
      technology: "Fintech leader (Nubank, PIX) but limited deep tech",
      costCompetitiveness: "Low wages but poor productivity and infrastructure",
      leadershipQuality: "Lula experienced but polarising, policy reversals likely",
    },
    investment: {
      signal: "Watch",
      reasoning: "Extraordinary natural resources and growing food export role. But governance challenges, political instability, and BRL volatility create risk.",
      relatedAssets: ["EWZ", "VALE", "PBR"],
    },
  },
  {
    name: "Japan",
    code: "JP",
    allianceCamp: "us_nato",
    unAlignmentUS: 85,
    unAlignmentChina: 15,
    primaryTradePartner: "China/US",
    keyTreaties: "US-Japan Security Treaty, Quad, CPTPP",
    stability: "Stable",
    trend: "Moving toward US bloc",
    scores: {
      education: 8, competitiveness: 7, economicOutput: 7, military: 6,
      tradeShare: 6, financialCenter: 7, reserveCurrency: 5, debtLevels: 2,
      wealthGaps: 7, politicalCohesion: 7, ruleOfLaw: 9, infrastructure: 9,
      characterValues: 9, naturalResources: 2, alliances: 8, technology: 8,
      costCompetitiveness: 6, leadershipQuality: 6,
    },
    scoreTrends: {
      education: "stable", competitiveness: "stable", economicOutput: "down", military: "up",
      tradeShare: "stable", financialCenter: "stable", reserveCurrency: "stable", debtLevels: "down",
      wealthGaps: "stable", politicalCohesion: "stable", ruleOfLaw: "stable", infrastructure: "stable",
      characterValues: "stable", naturalResources: "stable", alliances: "up", technology: "stable",
      costCompetitiveness: "up", leadershipQuality: "stable",
    },
    scoreEvidence: {
      education: "Top PISA scores, strong STEM pipeline, but shrinking student population",
      competitiveness: "Still 3rd largest economy, strong automotive/robotics/materials",
      economicOutput: "$4.2T GDP but stagnant growth, yen weakness flatters dollar terms",
      military: "Doubling defence to 2% GDP by 2027, counter-strike capability, Quad",
      tradeShare: "Major exporter but China dependency creates tension",
      financialCenter: "Tokyo Stock Exchange world's 4th largest, BOJ policy influential",
      reserveCurrency: "Yen 5% of global reserves, third most traded currency",
      debtLevels: "263% debt-to-GDP — worst in developed world, but domestically held",
      wealthGaps: "Relatively equal compared to US/UK, but poverty among elderly rising",
      politicalCohesion: "Stable LDP dominance, low social conflict, aging concerns",
      ruleOfLaw: "Strong judiciary, contract enforcement excellent",
      infrastructure: "World-class — Shinkansen, fiber broadband 99%, meticulously maintained",
      characterValues: "Discipline, quality focus, long-term thinking, social harmony",
      naturalResources: "Almost none — imports 90% of energy, food import dependent",
      alliances: "US treaty ally, Quad, growing defence ties with UK/Australia",
      technology: "Robotics leader, materials science, but lagging in software/AI",
      costCompetitiveness: "Weak yen making Japan competitive again for manufacturing",
      leadershipQuality: "Competent but cautious, BOJ policy normalisation ongoing",
    },
    investment: {
      signal: "Watch",
      reasoning: "Defence spending surge and weak yen boost competitiveness. But world's worst debt burden and demographic decline create structural headwinds.",
      relatedAssets: ["EWJ", "DXJ", "HEWJ"],
    },
  },
  {
    name: "Turkey",
    code: "TR",
    allianceCamp: "neutral",
    unAlignmentUS: 30,
    unAlignmentChina: 45,
    primaryTradePartner: "EU/Russia",
    keyTreaties: "NATO, EU customs union (partial)",
    stability: "Volatile",
    trend: "Becoming more neutral",
    scores: {
      education: 5, competitiveness: 5, economicOutput: 4, military: 7,
      tradeShare: 3, financialCenter: 3, reserveCurrency: 1, debtLevels: 5,
      wealthGaps: 4, politicalCohesion: 4, ruleOfLaw: 3, infrastructure: 6,
      characterValues: 5, naturalResources: 4, alliances: 5, technology: 4,
      costCompetitiveness: 7, leadershipQuality: 4,
    },
    scoreTrends: {
      education: "stable", competitiveness: "up", economicOutput: "stable", military: "up",
      tradeShare: "stable", financialCenter: "stable", reserveCurrency: "stable", debtLevels: "stable",
      wealthGaps: "down", politicalCohesion: "down", ruleOfLaw: "down", infrastructure: "stable",
      characterValues: "stable", naturalResources: "stable", alliances: "down", technology: "up",
      costCompetitiveness: "up", leadershipQuality: "down",
    },
    scoreEvidence: {
      education: "Young population, improving universities, but brain drain to EU",
      competitiveness: "Lira collapse made exports cheap, manufacturing growing",
      economicOutput: "$1.1T GDP, 19th largest, but inflation ravaged purchasing power",
      military: "NATO's second largest army, drone warfare pioneer (Bayraktar TB2)",
      tradeShare: "Small share but strategic trade corridor between Europe and Asia",
      financialCenter: "Istanbul limited by lira instability and capital flight",
      reserveCurrency: "TRY collapsed 80% since 2020, not a reserve currency",
      debtLevels: "Government debt 35% GDP (low) but corporate FX debt high",
      wealthGaps: "Middle class eroded by 80%+ inflation over 3 years",
      politicalCohesion: "Erdogan consolidated power but opposition growing, Kurdish issue",
      ruleOfLaw: "Judiciary politicised, property rights uncertain for foreign investors",
      infrastructure: "Major investment in airports, bridges, tunnels — Istanbul Airport world's largest",
      characterValues: "Entrepreneurial culture, strategic geographic position",
      naturalResources: "Limited — energy importer, some mining, agriculture",
      alliances: "NATO member but bought Russian S-400, plays both sides",
      technology: "Drone tech leader, automotive growing, but limited in deep tech",
      costCompetitiveness: "Ultra-cheap labour after lira collapse — attracting FDI",
      leadershipQuality: "Erdogan unpredictable, unorthodox economics, but pragmatic on foreign policy",
    },
    investment: {
      signal: "Watch",
      reasoning: "Strategic NATO position and ultra-cheap currency attract capital. But lira volatility, inflation legacy, and political risk require careful timing.",
      relatedAssets: ["TUR", "BIST100"],
    },
  },
];

export function getOverallScore(scores: Record<string, number>): number {
  const values = Object.values(scores);
  return Math.round((values.reduce((a, b) => a + b, 0) / values.length) * 10) / 10;
}

export function getStrongestDeterminant(scores: Record<string, number>): string {
  const entries = Object.entries(scores);
  entries.sort((a, b) => b[1] - a[1]);
  return DETERMINANT_LABELS[entries[0][0]] || entries[0][0];
}

export function getWeakestDeterminant(scores: Record<string, number>): string {
  const entries = Object.entries(scores);
  entries.sort((a, b) => a[1] - b[1]);
  return DETERMINANT_LABELS[entries[0][0]] || entries[0][0];
}
